apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
        requests:
          disk.csi.azure.com/mount-replicas: 1
        limits:
          disk.csi.azure.com/mount-replicas: 1
